### ISSUE TITLE
Integrate into phy

### ISSUE THREAD

**Issue by nippoo** [klusta-team/klustakwik2#1]
Eventually we're going to want to integrate the KK2 code into the new IPython-based framework for ephys data, https://github.com/kwikteam/phy - but given that we haven't written up a proper document for coding style / contributing and a framework for loading and saving data yet, probably easiest to develop here and then move across when the project's more mature.

**Comment by rossant** [comment]
+1

**Comment by thesamovar** [comment]
I think we decided it was better to keep the repos separate, so closing this.
