### ISSUE TITLE
Check for and break out of cycles

### ISSUE THREAD

**Issue by thesamovar** [klusta-team/klustakwik2#11]
They shouldn't happen, but it's good to detect if they do. Easy to implement with a set of hash(kk.clusters).

**Comment by nippoo** [comment]
How do you break out of them? Randomly switch around some spikes? ;)

**Comment by thesamovar** [comment]
That remains to be seen! Various strategies could be applied...

**Comment by thesamovar** [comment]
Reopened for further discussion.
