### ISSUE TITLE
Make sure that results are corrects

### ISSUE THREAD

**Issue by thesamovar** [klusta-team/klustakwik2#17]
At the moment they're not. The test `test_synthetic_4d_easy_non_gaussian` for example works fine in KK1 but not in KK2.

From extensive testing, I'm pretty confident that the following are correct (there are slight differences to KK1 but that's because of switching to a sparse algorithm):
- Loading data
- Mask starts
- M-step (weights, cluster means, covariance matrices)
- Cholesky (verified with several tests)
- TriSolve (verified with tests)
- InvCovDiag (verified to be the diagonal of the inverse of the covariance matrix)

**Comment by nippoo** [comment]
We should have unit tests for simple cases where the results are well-known
(or test that they are similar enough to a known good clustering...)

**Comment by thesamovar** [comment]
Yep, that's the idea of `tests/test_synthetic_data.py`. I'm using the one that doesn't pass to debug.

**Comment by shabnamkadir** [comment]
I'm just linking to the test in question to make things easier to find:

https://github.com/klusta-team/klustakwik2/blob/master/klustakwik2/tests/test_synthetic_data.py#L130-L149

**Comment by thesamovar** [comment]
Clearly this is not an early morning lab...

**Comment by rossant** [comment]
Almost not

**Comment by thesamovar** [comment]
OK found a fairly major bug and fixed it. The results were being returned in a somewhat random order. It's still not behaving the same as KK1 but this is a big step in sorting out the problem!

So far, it seems as though the E-step is giving more or less the same results as KK1. Some slight differences are to be expected, but it seems pretty much consistent (e.g. chol matrix is within 0.1% of the value in KK1, etc.).

It could be the case that splitting is not working correctly.

**Comment by thesamovar** [comment]
OK with the latest changes it seems as though the problems might be solved. Needs to be run on some real data now.

**Comment by thesamovar** [comment]
From the data we've looked at so far, it seems as though KK2 is performing as well if not better than KK1, and so I'm going to close this issue now and we can open new issues for specific bugs.
