### ISSUE TITLE
Consider using Blosc to compress data

### ISSUE THREAD

**Issue by thesamovar** [klusta-team/klustakwik2#2]
One of the ideas for KK2 is to keep some large arrays on a memory mapped file rather than in RAM. Using the Blosc compressor could lead to some big speed improvements with this. http://www.blosc.org/

**Comment by kdharris101** [comment]
Interesting idea!

To be clear: is this to speed up RAM access; or to allow use on machines with less RAM but having an SSD?

**Comment by thesamovar** [comment]
It could be used to speed up RAM access but I was rather thinking about the fact that we will need (for >300 channels) to put quite a lot of data on to disk rather than RAM (LogP in particular is going to be huge, but only infrequently read/written). I'm guessing that this will create a bottleneck that Blosc could help with.

**Comment by thesamovar** [comment]
This is no longer necessary or useful I think.
