### ISSUE TITLE
Set up travis

### ISSUE THREAD

**Issue by rossant** [klusta-team/klustakwik2#41]
@nippoo want to do it? (required by #40...)

**Comment by nippoo** [comment]
Let's wait until we've figured out what we're doing with #40 ...

**Comment by rossant** [comment]
we might need that before merging the py3 PR..?

**Comment by nippoo** [comment]
OK this is done now - sorry for pushing it straight to master, but AFAIK I had to do that to test the first build! Give me a sec and I'll update the py3 PR.

**Comment by rossant** [comment]
can you add a travis badge in readme (like in phy) to see if the build fails or succeeds?
