### ISSUE TITLE
Compile Cython in setup.py instead of pyximport

### ISSUE THREAD

**Issue by rossant** [klusta-team/klustakwik2#42]
This might simplify packaging on the various platforms, compared to `pyximport`
(@mstimberg any opinion on this?)

**Comment by mstimberg** [comment]
I think it is preferable to do this in `setup.py`, this will also allow you to easily build binary packages (e.g. for conda). It's normally really straightforward: http://docs.cython.org/src/reference/compilation.html#compiling-with-distutils

The only thing that makes our setup script in Brian 2 a bit complicated is that we allow installation without Cython from the source package, i.e. we support both building from a `.pyx` file (when building from the source directly from github) and building fom the `.cpp` file (when building from the source package). In retrospect, I think it'd be just fine to simply build-depend on Cython...

**Comment by thesamovar** [comment]
I agree this would be better: I only didn't do it yet because I'm lazy.
