### ISSUE TITLE
graceful break

### ISSUE THREAD

**Issue by nsteinme** [klusta-team/klustakwik2#5]
Hey Dan - this isn't really a "KK2" issue but I'll put it here anyway since it's what's under active development - 

It would be great if there were a way to stop the clustering gracefully, i.e. you could press some button and it would stop the algorithm, write out the current state of clustering as the ".clu.N" file, and return successfully. Currently the only option to stop midway is ctrl+C. This option is problematic because then you have to do whatever post-cluster processing remained yourself (in my case, adding the temp.clu.N file to the kwik file, assuming a recent temp.clu had indeed been saved), because it often seems to end up in corrupted kwik file (this is not KK's fault, I realize, but would probably be solved with a graceful break), and because it won't just move on to the next dataset to cluster (i.e. next shank; again, not KK's fault). The manual break is desirable because I've been noticing in more and more of my KK jobs just how large a percent of time is spent on the final tiny bit of clustering (which one doesn't care so much about). In the future this could be incorporated into a GUI that updated with the progress of the clustering, so you could see whether you might already be satisfied with the state of it, and click to move on before the defined endpoint (nChanged=0 + no changes in trysplits) was reached. 

Thanks - 

Nick

**Comment by thesamovar** [comment]
This should be straightforward to do - thanks for the suggestion!

**Comment by nsteinme** [comment]
Cool, thanks. One other note on this - if the "subset" option is employed, it should assign all the original spikes to nearest clusters (or whatever it does) before writing the .clu.N (i.e., just writing whatever would have been written to a temp.clu at that point is not useful if the subset option has been used, since the temp.clu doesn't have all the spikes).

**Comment by thesamovar** [comment]
Sure thing - but we'll probably be rethinking/redesigning the subset option anyway (maybe to make it take less RAM as well as less time).

**Comment by thesamovar** [comment]
Other than the subset issue, I think this is now all covered so I'm closing this issue.
