### ISSUE TITLE
different input and output filenames

### ISSUE THREAD

**Issue by nsteinme** [klusta-team/klustakwik2#57]
Currently, specifying to use name.fet.1 and name.fmask.1 produces name.clu.1 and name.klg.1. Instead, should be able to specify that the algorithm will work with the data in name.fet.1 and name.fmask.1 but produce name2.clu.1 and name2.klg.1. This would avoid the need to duplicate either the fet/fmask or the clu/klg when running a second time on a given dataset.

**Comment by thesamovar** [comment]
This isn't too much effort to implement, but I think we'll probably soon switch to primarily using phy on kwik files rather than fet/fmask/clu files. @rossant @nippoo ?

**Comment by rossant** [comment]
@nsteinme how would you want it to work exactly with phy?

**Comment by nippoo** [comment]
Yep, this is definitely an issue for phy! Thankfully the KWIK format already supports multiple clusterings within the same file, so this could just be from the command-line script:

`phy cluster-auto --clustering-name=kk_test_1 myexperiment.kwik` or whatever you want to call it.

In fact I think the only change we need to make, is saving the KlustaKwik parameters _with_ the clustering in a notionally read-only way, so you can just create loads of clusterings with a numerical UUID, and distinguish between them using the parameters (i.e. you could imagine a dataset with 100 different clusterings or so, for 3-4 different values of half a dozen different parameters - having loads of .clus would just get really confusing)

**Comment by thesamovar** [comment]
@nsteinme would you be happier using fet/fmask/clu or would @nippoo's suggestion work for you?

**Comment by nippoo** [comment]
Or a similar argument to the `clustering.run()` function - default options `run(algorithm='klustakwik2', clustering='main')`

**Comment by nsteinme** [comment]
I'm definitely on board with the kwik version of this, and the way that Max
described it using the multiple clusterings is the way I was thinking of
it. If we're ready to go with that in the short term, then great, we can
forget this issue and forget the fet/fmask.

**Comment by thesamovar** [comment]
OK, sounds like a plan. Closing this issue.

**Comment by rossant** [comment]
see https://github.com/kwikteam/phy/issues/333
