### ISSUE TITLE
kluster .raw.kwd files

### ISSUE THREAD

**Issue by lepmik** [klusta-team/klustakwik2#61]
I am using the open ephys system and saving files in the kwik format. It would be really nice to be able to kluster these files directly with klustakwik

**Comment by thesamovar** [comment]
This is now working using the phy package (https://github.com/kwikteam/phy), although it is not documented yet. There will quite soon (within a week or two hopefully) be a new release of phy with this documented, and it will be announced on the klustaviewas email list.
