### ISSUE TITLE
Can you release a new version on Pypi without the log at import?

### ISSUE THREAD

**Issue by alejoe91** [klusta-team/klustakwik2#78]
Thanks :)

**Comment by rossant** [comment]
Sorry I'm a bit swamped at the moment, would you mind giving me your pypi login so that I add you as a maintainer? I can also do the same for this GitHub project if you want. Thanks!

**Comment by alejoe91** [comment]
That would be awesome :)

I can help you out with phy as well if you want. 
We are in a continuous state of testing both on linux and windows machines (another PR regarding WindowsPath is on its way for phy and phylib!)

My pypi name is `alejoe91`

**Comment by rossant** [comment]
excellent, thanks! done for pypi

**Comment by alejoe91** [comment]
just noticed that the pypi version is 0.2.6, while the git version i v0.2.5.

**Comment by rossant** [comment]
let's do 0.2.7 then?

**Comment by alejoe91** [comment]
sounds good, but I would need access to the github repo as well, right?

**Comment by rossant** [comment]
yep, you didn't receive the invite?

**Comment by rossant** [comment]
https://github.com/kwikteam/klustakwik2/invitations

**Comment by alejoe91** [comment]
got it now :) Thanks!

**Comment by alejoe91** [comment]
@rossant 

Ever seen this?

```
HTTPError: 400 Client Error: Binary wheel 'klustakwik2-0.2.7-cp36-cp36m-linux_x86_64.whl' has an unsupported platform tag 'linux_x86_64'. for url: https://upload.pypi.org/legacy/
```

**Comment by rossant** [comment]
Nope but I'm not really surprised, the last KK2 release is quite old and pypi/the Python setup API have changed a bit since then. My guess is that `setup.py` and the build process has to be upgraded somehow

**Comment by alejoe91** [comment]
Ok I'll try to look into that :)

**Comment by alejoe91** [comment]
ok, I had to use a manylinux docker and repair the wheel for manylinux. Seems to work on testpypi.

Is it ok if I upload a 2.7 and 3.6 versions?

**Comment by alejoe91** [comment]
or also a 3.7?

**Comment by rossant** [comment]
yep, 3.7 would be great too, this is what I'm using for development of phy 2

**Comment by alejoe91** [comment]
ok I'll upload all 3 then: 2.7, 3.6, 3.7

**Comment by alejoe91** [comment]
ok they should be up and running :)

**Comment by alejoe91** [comment]
tested and working! closing
